In [1]:
import numpy as np

In [2]:
dvalues = np.array( [ [1., 1., 1.], [2., 2., 2.], [3., 3., 3.,]])
inputs = np.array([[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2], [-1.5, 2.7, 3.3, -0.8]])

dweights = np.dot(inputs.T, dvalues)
print(dweights)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


In [4]:
dvalues = np.array( [ [1., 1., 1.], [2., 2., 2.], [3., 3., 3.,]])
biases = np.array([[2, 3, 0.5]])

dbiases = np.sum(dvalues, axis=0, keepdims=True)
print(dbiases)

[[6. 6. 6.]]


In [5]:
dvalues = np.array( [ [1., 1., 1.], [2., 2., 2.], [3., 3., 3.,]])
weights = np.array([[0.2, 0.8, -0.5, 1.], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]])

dweights = np.dot(dvalues, weights.T)
print(dweights)


ValueError: shapes (3,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)