Gradient of Loss With respect to Weights

In [10]:
import numpy as np
dL_dZValues = np.array([ [1., 1., 1.],[2., 2., 2.], [3., 3., 3.]])

inputs = np.array([[1, 2, 3, 2.5], [2., 5. , -1., 2.], [-1.5, 2.7, 3.3, -0.8] ])

dL_dW = np.dot(inputs.T , dL_dZValues)
print(dL_dW)


[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


Graient of loss with respect to Biases

In [12]:
import numpy as np
dL_dZValues = np.array([ [1., 1., 1.],[2., 2., 2.], [3., 3., 3.]])

biases = np.array([2, 3, 0.5])

dL_dBiases = np.sum(dL_dZValues, axis=0, keepdims=True)
print(dL_dBiases)

[[6. 6. 6.]]


Gradient of loss with respect to INPUTS

In [ ]:
import numpy as np
dL_dZValues = np.array([ [1., 1., 1.],[2., 2., 2.], [3., 3., 3.]])

weights = np.array([[0.1, 0.2, 0.3, 0.4], [0.5, 0.6, 0.7, 0.8], [0.9, 1.0, 1.1, 1.2]])

dL_dX = np.dot(weights.T, dL_dZValues)
print(dL_dX)