Gradient of Loss With respect to Weights

In [10]:
import numpy as np
dL_dZValues = np.array([ [1., 1., 1.],[2., 2., 2.], [3., 3., 3.]])

inputs = np.array([[1, 2, 3, 2.5], [2., 5. , -1., 2.], [-1.5, 2.7, 3.3, -0.8] ])

dL_dW = np.dot(inputs.T , dL_dZValues)
print(dL_dW)


[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


Graient of loss with respect to Biases

In [12]:
import numpy as np
dL_dZValues = np.array([ [1., 1., 1.],[2., 2., 2.], [3., 3., 3.]])

biases = np.array([2, 3, 0.5])

dL_dBiases = np.sum(dL_dZValues, axis=0, keepdims=True)
print(dL_dBiases)

[[6. 6. 6.]]


Gradient of loss with respect to INPUTS

In [16]:
import numpy as np
dL_dZValues = np.array([ [1., 1., 1.],[2., 2., 2.], [3., 3., 3.]])
W = np.array([ [0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]).T

dL_dX = np.dot(dL_dZValues, W.T)
print(dL_dX)

[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]
