In [16]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01* np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

X, y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2,3)
dense1.forward(X)

print(dense1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]


ACTIVATION FUNCTION: RELU


In [11]:
import numpy as np
inputs = [ 0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
outputs = np.maximum(inputs, 0)
print(outputs)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [12]:
# ReLU Activation 
class Activation_ReLU:
    # forward pass
    def forward(self, inputs):
        # Calculate output values from input
        self.output = np.maximum(inputs, 0)

In [18]:
from nnfs.datasets import spiral_data
# create data sets 
X, y = spiral_data( samples=100, classes=3)

# Create Dense layer with 2 inputs features and 3 output values
dense1 = Layer_Dense(2, 3)

# Create ReLU Activation to be used with dense layer.
activation1 = Activation_ReLU()

# Make forward pass of our training data through this layer
dense1.forward(X)

# Forward pass through activation function.
# Take in output from previous layer
activation1.forward(dense1.output)

# Let's see output of the first few sample:
print(activation1.output[:5])



[[0.         0.         0.        ]
 [0.00013767 0.         0.        ]
 [0.00022187 0.         0.        ]
 [0.0004077  0.         0.        ]
 [0.00054541 0.         0.        ]]


ACTIVATION SOFTMAX FUNCTION

In [30]:
## Try These Excercises For Yourself
A = [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
print(np.sum(A))

# For One Dimensional along Rows
print('Sum along row:',np.sum(A, axis=0))

# For One Dimensional along Columns
print('Sum along columns:', np.sum(A, axis=1))

#For 2 dimensional
print('In two dimensional along rows: ', np.sum(A, axis=0, keepdims=True))
print(np.sum(A, axis=0, keepdims=True).shape)
#For 2 dimensional
print('In two dimensional along columns: ', np.sum(A, axis=1, keepdims=True))
print(np.sum(A, axis=1, keepdims=True).shape)


78
Sum along row: [15 18 21 24]
Sum along columns: [10 26 42]
In two dimensional along rows:  [[15 18 21 24]]
(1, 4)
In two dimensional along columns:  [[10]
 [26]
 [42]]
(3, 1)
