BUILDING NEURAL NETWORKS FROM SCRATCH PART 1: CODING NEURONS AND LAYERS

In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

In [7]:
# Dense layer Class
class Layer_Dense:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

# Forward Pass
    def forward(self, inputs):
       # inputs (batch_size × n_inputs)
        # weights (n_inputs × n_neurons)
        # result → (batch_size × n_neurons)
        self.output = np.dot(inputs, self.weights) + self.biases


# Create datasets 
X, y = spiral_data(samples=100, classes=3)
# Create dense layer
dense1 = Layer_Dense(2, 3)
dense1.forward(X)
print(dense1.output[: 3])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-4.3361859e-05 -8.5417814e-05 -9.9373065e-05]
 [-7.3564916e-05  1.4769069e-05 -1.5383620e-04]]


ACTIVATION FUNCTION : RELU

In [10]:
inputs = [0, 2, -1, 3, -2.7, 1.1, 2.8, -0.9, 1.0]
output = np.maximum(0, inputs)
print(output)

[0.  2.  0.  3.  0.  1.1 2.8 0.  1. ]


In [11]:
# RELU ACTIVATION
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [ ]:
# Create dataset
X, y = spiral_data(samples=100, classes=3)
# Create Dense Layer with 2 input features and 3 output values
dense1 = Layer_Dense(2,3)

#Create ReLU activation (to be used with Dense layer)
activation1 = Activation_ReLU()

# Make a forward pass of our training data through this layer
dense1.forward(X)

# Forward pass through activation function
# Takes in output from previous layer
activation1.forward(dense1.output)

print(activation1.output[: 5])

[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 5.1996012e-05]
 [0.0000000e+00 0.0000000e+00 9.6249794e-05]
 [0.0000000e+00 0.0000000e+00 2.1596655e-04]
 [0.0000000e+00 1.6060306e-04 4.8348506e-05]]
