BUILDING NEURAL NETWORKS FROM SCRATCH PART 1: CODING NEURONS AND LAYERS

In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

In [7]:
# Dense layer Class
class Layer_Dense:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

# Forward Pass
    def forward(self, inputs):
       # inputs (batch_size × n_inputs)
        # weights (n_inputs × n_neurons)
        # result → (batch_size × n_neurons)
        self.output = np.dot(inputs, self.weights) + self.biases


# Create datasets 
X, y = spiral_data(samples=100, classes=3)
# Create dense layer
dense1 = Layer_Dense(2, 3)
dense1.forward(X)
print(dense1.output[: 3])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-4.3361859e-05 -8.5417814e-05 -9.9373065e-05]
 [-7.3564916e-05  1.4769069e-05 -1.5383620e-04]]


ACTIVATION FUNCTION : RELU

In [10]:
inputs = [0, 2, -1, 3, -2.7, 1.1, 2.8, -0.9, 1.0]
output = np.maximum(0, inputs)
print(output)

[0.  2.  0.  3.  0.  1.1 2.8 0.  1. ]


In [11]:
# RELU ACTIVATION
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [14]:
# Create dataset
X, y = spiral_data(samples=100, classes=3)
# Create Dense Layer with 2 input features and 3 output values
dense1 = Layer_Dense(2,3)

# Create ReLU activation (to be used with Dense layer)
activation1 = Activation_ReLU()

# Make a forward pass of our training data through this layer
dense1.forward(X)

# Forward pass through activation function
# Takes in output from previous layer
activation1.forward(dense1.output)

print(activation1.output[:5])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ACTIVATION FUNCTION : SOFTMAX

In [15]:
inputs = [ [1, 2, 3, 2.5], [2.0, 5.0, -1, 2], [-1.5, 2.7, 3.3, -0.8]]
exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
print(probabilities)
np.sum(probabilities, axis=1)

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]


array([1., 1., 1.])

In [ ]:
# Softmax activation
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp( inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities
      

# One Forward Pass (Without Loss)

In [ ]:
X, y = spiral_data(samples=100, classes=3)
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])


[[0.33333334 0.33333334 0.33333334]
 [0.33333328 0.33333337 0.33333337]
 [0.3333333  0.33333334 0.33333337]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333278 0.33333355 0.3333337 ]
 [0.33333236 0.3333337  0.33333397]
 [0.33333185 0.33333293 0.33333525]
 [0.33333176 0.33333388 0.33333433]
 [0.3333312  0.3333339  0.3333349 ]
 [0.333331   0.3333337  0.33333534]
 [0.33333334 0.33333334 0.33333334]
 [0.33333075 0.33333424 0.333335  ]
 [0.3333304  0.3333344  0.33333525]
 [0.33333024 0.33333442 0.3333353 ]
 [0.33333036 0.33333188 0.33333772]
 [0.33333147 0.33333004 0.33333853]
 [0.3333294  0.3333347  0.33333588]
 [0.33332938 0.33333263 0.33333802]
 [0.33333012 0.33333057 0.33333933]
 [0.33332878 0.33333313 0.33333808]
 [0.33332914 0.33333483 0.33333606]
 [0.33332956 0.3333302  0.33334023]
 [0.33332834 0.3333322  0.33333945]
 [0.33332765 0.3333343  0.333338  ]
 [0.3333332  0.3333268  0.33334002]
 [0.33333513 0.33332708 0.33333778]
 [0.33333328 0.33332625 0.33