# In the code , we will run the Linear layer by using Pytorch

In [20]:
import torch

In [21]:
x = torch.rand(100,2, dtype=torch.float32)
print(x[:5])

tensor([[0.4046, 0.2196],
        [0.3463, 0.1890],
        [0.2073, 0.3215],
        [0.3128, 0.9910],
        [0.4482, 0.4615]])


In [22]:
class Linear:
    def __init__(self, n_inputs, n_neurons):
        self.weights = torch.rand(n_inputs, n_neurons, dtype=torch.float32)
        self.bias = torch.zeros((1, n_neurons), dtype=torch.float32)

    def forward(self, inputs):
        self.output = torch.matmul(inputs, self.weights)+self.bias

In [33]:
linear1 = Linear(x.shape[1], 6)
linear1.forward(x)
print(linear1.output[:4])

linear2 = Linear(linear1.output.shape[1], 3)
linear2.forward(linear1.output)
print(linear2.output[:4])

linear3 = Linear(linear2.output.shape[1], 1)
linear3.forward(linear2.output)
print(linear3.output[:4])

tensor([[0.3671, 0.3773, 0.3614, 0.3289, 0.4156, 0.3387],
        [0.3150, 0.3234, 0.3102, 0.2823, 0.3563, 0.2908],
        [0.3618, 0.2836, 0.3515, 0.3327, 0.3391, 0.3497],
        [0.9664, 0.6466, 0.9331, 0.8996, 0.8171, 0.9541]])
tensor([[1.2856, 1.0997, 1.0763],
        [1.1029, 0.9433, 0.9232],
        [1.1895, 1.0031, 0.9500],
        [3.0802, 2.5784, 2.3985]])
tensor([[1.4942],
        [1.2817],
        [1.3621],
        [3.4998]])
