In [1]:
import numpy as np

In [2]:
dvalues = np.array( [ [1., 1., 1.], [2., 2., 2.], [3., 3., 3.,]])
inputs = np.array([[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2], [-1.5, 2.7, 3.3, -0.8]])

dweights = np.dot(inputs.T, dvalues)
print(dweights)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


In [4]:
dvalues = np.array( [ [1., 1., 1.], [2., 2., 2.], [3., 3., 3.,]])
biases = np.array([[2, 3, 0.5]])

dbiases = np.sum(dvalues, axis=0, keepdims=True)
print(dbiases)

[[6. 6. 6.]]


In [9]:
dvalues = np.array( [ [1., 1., 1.], [2., 2., 2.], [3., 3., 3.,]])
# we have 3 sets of weights - one set for each neurons
# we have 4 inputs, thus 4 weights
weights = np.array([[0.2, 0.8, -0.5, 1.], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]).T

dweights = np.dot(dvalues, weights.T)
print(dweights)


[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]


# Adding Backward Method in the layer-Dense class

In [11]:
# Dense Layer
class Layer_Dense:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    # Forward Pass
    def forward(self, inputs):
        # Remember Inputs
        self.inputs = inputs
        # Calculate output values from input ones, weights and biase = (W.X + B)
        self.output = np.dot(inputs, self.weights) + self.biases


    #Backward Pass
    def Backward(self, dvalues):
        # Gradient on parameters
        # For weights
        self.dweights = np.dot(self.inputs.T, dvalues)
        # For biases
        self.biases = np.sum(dvalues, axis=0, keepdims=True)
        #Gradient on values (inputs)
        self.dinputs = np.dot(dvalues, self.weights.T)