In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8, 8, 4], [7,9,5], [6,10,6], [5,12,7]], columns=['cgpa', 'profile_score', 'lpa'] )

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [22]:
import numpy as np

def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1, L):
        parameters['W' + str(l)] = np.ones((layer_dims[l], layer_dims[l-1])) * 0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

    return parameters

print(initialize_parameters([2, 2, 1]))

{'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1, 0.1]]), 'b2': array([[0.]])}


In [ ]:
def linear_forward(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b
    return Z

In [39]:
def L_layer_forward(X, parameters):
    A = X
    L = len(parameters) // 2

    for l in range(1, L+1):
        A_prev = A
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]

        print(f"A{l-1}: \n{A_prev}")
        print(f"W{l}: \n{Wl}")
        print(f"b{l}: \n{bl}")
        print("--"*20)

        A = linear_forward(A_prev, Wl, bl)
        print(f"A{l}: \n{A}")
        print("**"*20)

    return A, A_prev



In [42]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) #shape (no. of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initiatization
parameters = initialize_parameters([2,2,1])
# parameters
y_hat = L_layer_forward(X, parameters)


A0: 
[[8]
 [8]]
W1: 
[[0.1 0.1]
 [0.1 0.1]]
b1: 
[[0.]
 [0.]]
----------------------------------------
A1: 
[[1.6]
 [1.6]]
****************************************
A1: 
[[1.6]
 [1.6]]
W2: 
[[0.1 0.1]]
b2: 
[[0.]]
----------------------------------------


ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

In [30]:
X

array([[8],
       [8]])

In [31]:
y

np.int64(4)