BUILDING NEURAL NETWORKS FROM SCRATCH PART 1: CODING NEURONS AND LAYERS

In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

In [7]:
# Dense layer Class
class Layer_Dense:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

# Forward Pass
    def forward(self, inputs):
       # inputs (batch_size × n_inputs)
        # weights (n_inputs × n_neurons)
        # result → (batch_size × n_neurons)
        self.output = np.dot(inputs, self.weights) + self.biases


# Create datasets 
X, y = spiral_data(samples=100, classes=3)
# Create dense layer
dense1 = Layer_Dense(2, 3)
dense1.forward(X)
print(dense1.output[: 3])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-4.3361859e-05 -8.5417814e-05 -9.9373065e-05]
 [-7.3564916e-05  1.4769069e-05 -1.5383620e-04]]


ACTIVATION FUNCTION : RELU

In [10]:
inputs = [0, 2, -1, 3, -2.7, 1.1, 2.8, -0.9, 1.0]
output = np.maximum(0, inputs)
print(output)

[0.  2.  0.  3.  0.  1.1 2.8 0.  1. ]


In [11]:
# RELU ACTIVATION
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [14]:
# Create dataset
X, y = spiral_data(samples=100, classes=3)
# Create Dense Layer with 2 input features and 3 output values
dense1 = Layer_Dense(2,3)

# Create ReLU activation (to be used with Dense layer)
activation1 = Activation_ReLU()

# Make a forward pass of our training data through this layer
dense1.forward(X)

# Forward pass through activation function
# Takes in output from previous layer
activation1.forward(dense1.output)

print(activation1.output[:5])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ACTIVATION FUNCTION : SOFTMAX

In [15]:
inputs = [ [1, 2, 3, 2.5], [2.0, 5.0, -1, 2], [-1.5, 2.7, 3.3, -0.8]]
exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
print(probabilities)
np.sum(probabilities, axis=1)

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]


array([1., 1., 1.])

In [ ]:
# Softmax activation
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp( inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities
      

# One Forward Pass (Without Loss)

In [27]:
X, y = spiral_data(samples=100, classes=3)
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])


[[0.33333334 0.33333334 0.33333334]
 [0.33333266 0.3333335  0.33333385]
 [0.33333156 0.33333433 0.33333418]
 [0.33333084 0.3333342  0.33333492]
 [0.3333313  0.3333335  0.3333352 ]
 [0.33332995 0.33333415 0.33333594]
 [0.33332783 0.33333588 0.33333623]
 [0.33332905 0.33333412 0.33333683]
 [0.33332652 0.3333359  0.33333758]
 [0.3333312  0.33333224 0.33333656]
 [0.33332694 0.33333468 0.3333384 ]
 [0.33332413 0.33333665 0.33333918]
 [0.3333228  0.33333924 0.333338  ]
 [0.33332202 0.33333775 0.33334017]
 [0.3333213  0.33334005 0.33333862]
 [0.3333202  0.33334067 0.3333391 ]
 [0.3333211  0.33333918 0.33333975]
 [0.33331782 0.33334053 0.33334166]
 [0.3333184  0.33333862 0.3333429 ]
 [0.3333185  0.33333808 0.33334345]
 [0.3333174  0.33334225 0.33334035]
 [0.33331662 0.33334076 0.33334267]
 [0.33331826 0.33334145 0.33334032]
 [0.3333152  0.33334154 0.33334327]
 [0.3333161  0.3333422  0.33334172]
 [0.33331364 0.33334228 0.33334407]
 [0.33331195 0.3333453  0.33334273]
 [0.33330482 0.3333436  0.33