In [70]:
import numpy as np

In [71]:
# define inputs - 100 rows, 2 columns (100 samples, 2 features)
X = np.random.rand(100, 2)
print(X[:5])

[[0.8988583  0.35806857]
 [0.87798271 0.89053263]
 [0.51385736 0.49795489]
 [0.76723834 0.79896965]
 [0.92849129 0.99979549]]


In [72]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
     # initialize weights and biases
       self.weights = 0.01 * np.random.rand(n_inputs, n_neurons)
       self.biases = np.zeros((1, n_neurons)) #One bias per neuron

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
  
        

In [73]:
dense1 = Layer_Dense(2, 3)
dense1.forward(X)

dense2 = Layer_Dense(3, 10)
dense2.forward(dense1.output)

dense3 = Layer_Dense(10, 2)
dense3.forward(dense2.output)

dense4 = Layer_Dense(2, 1)
dense4.forward(dense3.output)

In [74]:
print(dense4.output[:5])
print(dense4.output.shape)

[[8.20736164e-08]
 [1.12604428e-07]
 [6.45096176e-08]
 [9.96465495e-08]
 [1.22563214e-07]]
(100, 1)


# 10 features with 200 samples in my inputs

In [75]:
X = np.random.rand(200, 10)
print(X[:10])

[[0.79094093 0.01024223 0.88544939 0.20690802 0.70253415 0.45515908
  0.23715742 0.64229586 0.908524   0.97570476]
 [0.71868745 0.30683782 0.51352466 0.07159551 0.51259285 0.76430506
  0.75293935 0.02419384 0.62497716 0.77309276]
 [0.29738452 0.74841227 0.47515745 0.00739593 0.81856332 0.09515983
  0.7062276  0.68349479 0.10245167 0.81940503]
 [0.14285429 0.27238924 0.58181036 0.38895479 0.12160503 0.79986889
  0.91024467 0.59380048 0.71863986 0.83027791]
 [0.7246038  0.52394563 0.88909418 0.89242291 0.82859626 0.42232802
  0.58904583 0.73044382 0.23329725 0.38530238]
 [0.93611961 0.43596377 0.56785699 0.03923895 0.10736851 0.21911563
  0.85671192 0.62543056 0.23224556 0.43123814]
 [0.3195522  0.72811653 0.10260997 0.38458824 0.01646057 0.87939075
  0.08903652 0.65393335 0.69095539 0.08688244]
 [0.17712262 0.879176   0.13815058 0.07914017 0.2689752  0.82815197
  0.22755984 0.19697934 0.11000105 0.26941615]
 [0.34551992 0.68795634 0.11633082 0.60442882 0.13560247 0.07273625
  0.05589252

In [76]:
class Dense_Layer:
    def __init__(self, inputs, neurons):
        self.weights = 0.01 * np.random.rand(inputs, neurons)
        self.biases = np.zeros((1, neurons))

    def forward(self, input):
        self.output = np.dot(input, self.weights) + self.biases


dense1 = Dense_Layer(10,20)
dense1.forward(X)

dense2 = Dense_Layer(20, 10)
dense2.forward(dense1.output)

dense3 = Dense_Layer(10,5)
dense3.forward(dense2.output)

dense4 = Dense_Layer(5,3)
dense4.forward(dense3.output)

final_output = Dense_Layer(3,1)
final_output.forward(dense4.output)

# print(dense1.output[:5])
# print(dense1.output.shape)

print(final_output.output[:5])
print(final_output.output.shape)

[[4.42032871e-08]
 [3.88848773e-08]
 [3.61853047e-08]
 [4.14943747e-08]
 [4.68521696e-08]]
(200, 1)
