In [2]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

🔹 Case 1: Weights stored as (inputs × neurons)
Shape: (inputs, neurons)
Each column = weights for one neuron

Convenient for coding (NNFS library uses this)

Forward pass:  𝑍 = 𝑋.𝑊 + 𝑏
Z=XW+b

✅ No transpose needed.

In [3]:
import numpy as np

# Take 2 inputs and 3 neurons
X = np.array([1, 2])
W = np.array([[0.2, 0.8, -0.5], [0.5, -0.9, 0.26]]) # shape (1,2) 1 sample, 2 features
B = np.array([2, 3, 0.5])

#Forward pss
Z = np.dot(X, W) + B
print("Final result:", Z)

Final result: [3.20000005 2.         0.52      ]


🔹 Case 2: Weights stored as (neurons × inputs)
2. Neurons × Inputs (this new case)
Shape: (neurons, inputs)

Each row = weights for one neuron

More common in textbooks

Forward pass:

𝑍 = 𝑋 𝑊 𝑇 +𝑏
Z= XWT +b

👉 Here we must transpose to align shapes.

In [4]:
X = np.array([1,2])
W = np.array([ [0.2, 0.5], [0.8, -0.9], [-0.5, 0.26]])
B = np.array([2, 3, 0.5])
Z = np.dot(X, W.T) + B
print(Z)

[3.20000005 2.         0.52      ]


In [5]:
#Dense layer

class Layer_dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
    X, y = spiral_data(samples=100, classes=3) 

dense1 = Layer_dense(2,3)
dense1.forward(X)
print(dense1.output[:5])



[[-0.02666883  0.02990897 -0.01039604]]


# I have 5 inputs - 4 neurons first hidden layer - 3 next - 2 next - 1 neuron final output layer


In [20]:
x = np.random.rand(5, 5)
print(x)
w1 = np.random.rand(4,5)
b1 = np.zeros(4)
print(b1)
print(w1)

[[0.13185204 0.70791746 0.70907211 0.61174841 0.67190702]
 [0.44751587 0.69607717 0.37832614 0.10003205 0.96025678]
 [0.07243445 0.01930061 0.97957325 0.14847809 0.25870232]
 [0.21552881 0.5799124  0.97575169 0.2730089  0.97007507]
 [0.02549735 0.88804371 0.70860884 0.27777367 0.89486319]]
[0. 0. 0. 0.]
[[0.02652255 0.62563662 0.32954271 0.96712113 0.1685764 ]
 [0.90148299 0.32993565 0.88923332 0.51245166 0.51062891]
 [0.38682715 0.53008894 0.94470748 0.89286225 0.6771144 ]
 [0.63902738 0.54836134 0.27268312 0.14826864 0.85630298]]


In [16]:
# 2nd hidden layer having 3 neurons
w2 = np.random.rand(3,4)
b2 = np.zeros(3)
print(w2)

[[0.91672702 0.11381664 0.63112554 0.132815  ]
 [0.37424458 0.32440486 0.68011554 0.79553475]
 [0.50393361 0.29624239 0.88596227 0.35187056]]


In [17]:
# 3rd hidden layer with 2 neurons
w3 = np.random.rand(2, 3)
b3 = np.zeros(2)
print(w3)

[[0.73839034 0.55536126 0.20151771]
 [0.5485191  0.51964283 0.34878266]]


In [18]:
# final 
w4 = np.random.rand(1, 2)
b4 = np.zeros(1)
print(w4)

[[0.02461996 0.1488293 ]]


In [21]:
# Convert lists to numpy array
x_arrays = np.array(x)
w1_array = np.array(w1)
w2_array = np.array(w2)
w3_array = np.array(w3)
w4_array = np.array(w4)
b1_array = np.array(b1)
b2_array = np.array(b2)
b3_array = np.array(b3)
b4_array = np.array(b4)


In [22]:
output1 = np.dot(x_arrays, w1_array.T) + b1_array
print(output1)

[[1.3849682  1.6395468  2.0972939  1.3318627 ]
 [0.830655   1.5111053  1.6390202  1.6079422 ]
 [0.52401495 1.1509243  1.2714024  0.5675266 ]
 [1.117647   1.8885524  2.2131886  1.5929582 ]
 [1.2092794  1.5453899  2.0039716  1.5039471 ]]


In [23]:
output2 = np.dot(output1, w2_array.T) + b2_array
print(output2)

[[2.9567926 3.536139  3.5104017]
 [2.1814592 3.1949751 2.884146 ]
 [1.4891635 1.8856628 1.9311317]
 [2.8478947 3.8034065 3.644006 ]
 [2.7489746 3.5132728 3.3718445]]


In [24]:
output3 = np.dot(output2, w3_array.T) + b3_array
print(output3)

[[4.85451   4.683754 ]
 [3.9663403 3.8627582]
 [2.5359652 2.470251 ]
 [4.9494543 4.8095036]
 [4.660438  4.509553 ]]


In [25]:
final_output = np.dot(output3, w4_array.T) + b4_array
print(final_output)

[[0.81659764]
 [0.67254275]
 [0.4300811 ]
 [0.8376504 ]
 [0.7858934 ]]
